### ISSUE TITLE
sqlite3.OperationalError: database is locked - working on Gabriel

### ISSUE THREAD

**Issue by isadenghien** [neurospin/soma-workflow#21]
Hi, 

We have recently the following pb by using soma_workflow on Gabriel :

```
Traceback (most recent call last):
  File "/home/user/anaconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/user/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/.local/lib/python2.7/site-packages/soma_workflow-2.9.0-py2.7.egg/soma_workflow/start_database_server.py", line 146, in <module>
    config.get_shared_temporary_directory())
  File "/home/user/.local/lib/python2.7/site-packages/soma_workflow-2.9.0-py2.7.egg/soma_workflow/start_database_server.py", line 42, in __init__
    shared_tmp_dir)
  File "/home/user/.local/lib/python2.7/site-packages/soma_workflow-2.9.0-py2.7.egg/soma_workflow/database_server.py", line 381, in __init__
    create_database(database_file)
  File "/homeuser/.local/lib/python2.7/site-packages/soma_workflow-2.9.0-py2.7.egg/soma_workflow/database_server.py", line 188, in create_database
    login VARCHAR(255) NOT NULL UNIQUE)''')
sqlite3.OperationalError: database is locked
```

I removed the soma_workflow-1.1.db and all files into "soma-workflow/transfered-files" and update the version of somawf. But the error persists. 

Is there anything else I can try ?

Thanks for your help :)
Isa

**Comment by denisri** [comment]
Which version of SWF did you exactly use, and how have you installed it ? I see in your path that you are using anaconda, and a SWF 2.9.0 egg, whereas 2.9 is not released (it's not on pypi): is it a tarball from github ?
Does it happen on one specific machine or is it a general problem ?
On Ubuntu 14.04 it sometimes happens to me that all SQlite databases are locked when sqlite files are on a NFS filesystem. When it happens, I can only fix the problem by rebooting my machine. I don't know if this could be the same problem here ?

**Comment by isadenghien** [comment]
I tried with 2.8 and the new version this morning (the error message is not exactly the same with 2.8). My somaworkflow is located into the ~/.local directory.
Yes, I get the version with a git clone and tape:

`python setup.py install --user` 

You're right I use a anaconda version. But it worked correctly before and other users have the same pb (and a similar configuration).

The pb occurs on the server side, so I cannot reboot it. I remove the file .db, so it could create a new one ?

Isa

**Comment by isadenghien** [comment]
Even if I use another python version, I have the same pb. Did you restart your soma_workflow.start_database_server recently on Gabriel ?

**Comment by denisri** [comment]
It seems really related to SQlite + NFS, and not to Soma-Workflow, since using only sqlite commands I can reproduce the problem on the server gabriel:
<pre>sqlite3 ~/new_database.db
SQLite version 3.3.6
Enter ".help" for instructions
sqlite> .tables
Error: database is locked</pre>
(the file ~/new_dababase.db does not exist or is empty, soma-workflow is in no way involved here)
Doing the same on a non-NFS filesystem doesn't produce an error:
<pre>sqlite3 /tmp/sqlite.db
SQLite version 3.3.6
Enter ".help" for instructions
sqlite> .tables
sqlite> CREATE TABLE toto (id INTEGER, toto TEXT);
sqlite> .tables
toto
sqlite> .dump toto
BEGIN TRANSACTION;
CREATE TABLE toto (id INTEGER, toto TEXT);
COMMIT;</pre>
so the server really needs fixing (or rebooting).
Denis

**Comment by isadenghien** [comment]
Thanks Denis, your test seems very clear.
I'm going to send a message to the root.
Isa

**Comment by isadenghien** [comment]
The root restarted the nfslock service and it works now.
Isa
